= docs.projectile.mx

The site is generated from the AsciiDoc files in the link:https://github.com/bbatsov/projectile/tree/master/doc[doc] folder of Projectile's GitHub repo and is published to https://docs.projectile.mx.
link:https://antora.org[Antora] is used to convert the manual into HTML.
The filesystem layout is described at https://docs.antora.org/antora/2.0/component-structure/

To make changes to the manual you simply have to change the files under `doc`.
The manual will be regenerated manually periodically.

Check out https://docs.antora.org/antora/2.0/install/install-antora/[the detailed installation instructions]
if you run into any problems.

== Building the Site

You can build the documentation locally from this repo.

[source]
----
$ cd docs.projectile.mx
$ make build
----

After you're done with the initial setup you can use `make` to push changes to the site:

[source]
----
$ make deploy
----

NOTE: You'll need commit access to the repository for this to work.

To check the generated site you can simply open `docs/index.html` in your favourite browser.

If you want to make changes to the manual's page structure you'll have to edit
link:https://github.com/bbatsov/projectile/blob/master/doc/modules/ROOT/nav.adoc[nav.adoc].
